package com.fox.one.pay.core.model

import com.google.gson.annotations.SerializedName
import java.io.Serializable

/**
 * class description here
 * @author xiaoming1109@gmail.com
 * @version 1.0.0
 * @since 2019-02-18
 */
data class ServiceTransferReqBody(
    /**
     * member_id
     */
    @SerializedName("to_member") var toMemberId: String?,
    /**
     * service = [payment|exchange|otc]
     */
    @SerializedName("service") var service: String?,
    /**
     * 用于划转的资产ID
     */
    @SerializedName("asset_id") var assetId: String,
    /**
     * 划转的资产数量
     */
    @SerializedName("amount") var amount: String,
    /**
     * memo
     */
    @SerializedName("memo") var memo: String,
    /**
     * trace id, generated by UUID
     */
    @SerializedName("trace_id") var traceId: String): Serializable {
    constructor():this("", "", "", "0", "", "")

    companion object {
        const val SERVICE_PAYMENT = "payment"
        const val SERVICE_EXCHANGE = "exchange"
        const val SERVICE_OTC = "otc"
    }
}